// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:926d5a07-e1d5-4b85-8ada-89a228f928f4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_PvBmmOn0E",
    "aws_user_pools_web_client_id": "7tkqhj15t8bfolp95b56rd42e4",
    "oauth": {},
    "aws_content_delivery_bucket": "iot-pool-project-envamplify",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://iot-pool-project-envamplify.s3-website.us-east-2.amazonaws.com",
    "aws_appsync_graphqlEndpoint": "https://psjb5eava5hgheajor2ncomfdi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qpvor76zorat3og3kxci7nu2py"
};


export default awsmobile;
